other(CI): clean up workflow (#233)
* rm requirements and update get optimum version

* optimum rbln version

* simplify workflow

* add openai

* fix

* refactor: rm comments

* rm condition for check-code-quality

* debug patch

* debug patch

* simplify

* rm requirements.txt

* rm setup.py and requiremets

* build without setup.py

* fix if

* fix dependency

* [skip core] [skip worker] fix installing vllm-rbln in pytest-arc

* [skip core] [skip worker] update runner

* [skip worker][skip core][skip openai] pypi mirror server

* [skip worker][skip core]for test

* [skip core][skip worker][skip openai]

* [skip core][skip worker][skip openai]separage each rsd cases

* [skip worker][skip openai][skip core]fix dispatch

* [skip worker][skip openai][skip core]fix dispatch

* [skip worker][skip core][skip openai] fix

* update runner

* name fix

* name fix

* move out build vllm-rbln

* fix path

diff --git a/.github/workflows/rbln_utils_get_optimum_version_ci.yaml b/.github/workflows/rbln_utils_get_optimum_version_ci.yaml
--- a/.github/workflows/rbln_utils_get_optimum_version_ci.yaml
+++ b/.github/workflows/rbln_utils_get_optimum_version_ci.yaml
@@ -16,9 +16,15 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Get optimum version from requirements.txt
+      - name: Get optimum version from requirements
         id: get_target_optimum_version
         run: |
-          OPTIMUM_RBLN_VERSION=$(grep '^optimum-rbln' requirements.txt | sed 's/optimum-rbln>=//')
-          echo "Found optimum-rbln version in requirements.txt: $OPTIMUM_RBLN_VERSION"
+          OPTIMUM_RBLN_VERSION=$(grep 'optimum-rbln' pyproject.toml | sed -n 's/.*optimum-rbln>=\([^"]*\).*/\1/p')
+          echo "Found optimum-rbln version in pyproject.toml: $OPTIMUM_RBLN_VERSION"
+
+          if [ -z "$OPTIMUM_RBLN_VERSION" ]; then
+            echo "Error: Could not find optimum-rbln version in pyproject.toml"
+            exit 1
+          fi
+
           echo "OPTIMUM_RBLN_VERSION=$OPTIMUM_RBLN_VERSION" >> $GITHUB_OUTPUT
